### ISSUE TITLE
[FEAT] Add Support for use existing App Service Plan

### ISSUE THREAD

**Issue by fdmsantos** [claranet/terraform-azurerm-app-service#10]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have two web apps and i want they use the same App Service Plan. I'm creating the two Web Apps via this module, so i need this future to be able to link them to the same App Service Plan

### New or Affected Resource(s)/Data Source(s)

module.service_plan

### Potential Terraform Configuration

```hcl
Add variable to indicate that pretend use existing service plan and a service_plan_id variable.

variable "use_existing_service_plan" {
  type        = bool
  default     = false
}

Add count metadata to module service plan and not run when use_existing_service_plan is true.
Need to index all references to module.service_plan.

I will try to find some time to do PR. If someone starts working on this, please let me know.
```

**Comment by Shr3ps** [comment]
I don't think this will add a real enhancement. It will "just" complexify a bit this module (which already has lots of options).

Did you check this example code that should fit what you want to achieve: https://github.com/claranet/terraform-azurerm-app-service/blob/master/examples/linux-web-app/modules.tf ?

**Comment by fdmsantos** [comment]
hi @Shr3ps tks for reply. Indeed i saw that example after open the issue.

I understand your point of view, so i will implement using your suggestion (using container-web-app module directly).

Thank you, i will close the issue.

**Comment by fdmsantos** [comment]
hi @Shr3ps ,

Sorry for reopen the discussion. I would like having the possibility choose if the second web app will be deployed in own service plan or using existing service plan.

With this approach using the submodules directly, i need duplicate the code for second web app (in my use case will be 3 web apps where i want give the possibility have it all in same service plan or no. We have two clients using this project and one wants all in same plan and the other not).

With this use case, do you think will worth add this enhancement? I really didn't want having two different code bases to the same web app.

In my use case, we are planning also add function app to this App Plan, so i would like have this also in that module.

What is your opinion?

**Comment by Shr3ps** [comment]
This might be easy to do using for_each over the sub-module like this:

```terraform
module "container_web_app" {
  source  = "claranet/app-service/azurerm//modules/container-web-app"

  for_each = {
    app1 = {
        service_plan_id = module.service_plan.service_plan_id
    }
    app2 = {
        service_plan_id = module.service_plan.service_plan_id
    }
  }


  name_suffix = each.key

  service_plan_id  = each.value.service_plan_id 

  docker_image = try(each.value.docker_image, {
    name = "python"
    tag = "latest"
  })

  ...
```

If that fit your needs, maybe updating example (or adding another example directoy) could be cool

**Comment by fdmsantos** [comment]
ok :) . Will forget this idea :). I wanted continuing manage service plan and web app together in this module (less code), but you are right, i can reach what i want if i use separate modules for service plans and web apps.
