### ISSUE TITLE
[FEAT] New release version 7.9.2

### ISSUE THREAD

**Issue by vladciobancai** [claranet/terraform-azurerm-app-service#16]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, 

It is possible a new release version of the module to be released ? includes below changes:
* https://github.com/claranet/terraform-azurerm-app-service/pull/14
* https://github.com/claranet/terraform-azurerm-app-service/pull/15

Thank you,
Vlad

### New or Affected Resource(s)/Data Source(s)

app_service_linux_container

**Comment by BzSpi** [comment]
Done https://github.com/claranet/terraform-azurerm-app-service/releases/tag/v7.9.2
