### ISSUE TITLE
[FEAT] Add Support to User Managed Identity

### ISSUE THREAD

**Issue by fdmsantos** [claranet/terraform-azurerm-app-service#3]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Module only supports System assigned Managed identity. I would like have the possibility also add User Managed Identities.

Also, I think the container_registry_managed_identity_client_id parameter don't have any effect/meaning if the managed identity passed in this parameter won't be created as User Managed Identity on Web App.

With this, i identity two new capabilities related with User Managed Identities:

1. Add possibility to create user managed identity. This will required new variables
2. Create automatically an user managed identity when the container_registry_managed_identity_client_id is not null. Don't need new variables.

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_web_app (container and linux module) and azurerm_windows_web_app

**Comment by Shr3ps** [comment]
Thanks for your issue, will you implement it in a PullRequest?

**Comment by fdmsantos** [comment]
> Thanks for your issue, will you implement it in a PullRequest?

I will be out in next few weeks. When i back, if no one did it, i will try to find some time to implement it.

Thanks

**Comment by fdmsantos** [comment]
Hi @Shr3ps , Does makes sense add variable to disable System Assigned Identity?

In my use case a i will use User Assigned Identity, so i would like have possibility don't have System Assigned Identity.

**Comment by Shr3ps** [comment]
Yeah, It would make sens.
I think best is to have one variable with 2 or 3 attributes about identities.
We do this on others modules:

```hcl
  dynamic "identity" {
    for_each = var.identity[*]
    content {
      type         = var.identity.type
      identity_ids = var.identity.identity_ids
    }
  }

## Identity variables
variable "identity" {
  description = "Map with identity block informations."
  type = object({
    type         = string
    identity_ids = list(string)
  })
  default = {
    type         = "SystemAssigned"
    identity_ids = []
  }
}
```

https://github.com/claranet/terraform-azurerm-linux-vm/blob/master/r-vm.tf#L47C1-L53C4

**Comment by fdmsantos** [comment]
Hi, Tks for help.

I think With that approach, isn't possible having System Assigned Identity and User Assigned identity together, and Azure Web App Allow this. 
What do you think using something like this (Follow the approach keep one variable to Identities):

`## Identity variables
variable "identity" {
  description = "Map with identity block informations."
  type = list(object({
    type         = string
    identity_ids = list(string)
  }))
  default = [{
    type         = "SystemAssigned"
    identity_ids = []
  }}
}`

Also, in Container Web App, i'm thinking Add AcrPull role to Selected Managed Identity.
This role will be added to system assigned identity if container_registry_use_managed_identity is configured to true and container_registry_managed_identity_client_id is ommited. If this variable isn't ommited, the Role will be added to User Assigned Identity.

Also like i said before, i'm planning Create automatically an user managed identity when the container_registry_managed_identity_client_id is not null. Because configuring only this variable doesn't work if the selected user assigned identity aren't in web app identities.

What is your feedback?

**Comment by fdmsantos** [comment]
Tks for the help.

Unfortunately, it seems isn't possible Create automatically an user managed identity when the container_registry_managed_identity_client_id is not null. Because to create user assigned identity i need the Identity Name and i only have the client id.

Data Source: azurerm_user_assigned_identity doesn't support searching by client id.
